#!/bin/bash
curl -L -o /tmp/v1.18.tar.gz https://github.com/google/leveldb/archive/v1.18.tar.gz
cd /tmp
tar -xzf v1.18.tar.gz
cd leveldb-1.18
make
cp -a lib*.so* /usr/lib && \
cp -a include /usr/ && \
cd ..
rm v1.18.tar.gz

